spring:
  datasource:
    url: jdbc:mysql://localhost:3306/store
    username: root
    password: パスワード
    driverClassName: com.mysql.jdbc.Driver
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: update
